name: electronics_store
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  path_provider: ^2.1.5
  window_size: ^0.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/json/
