// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:electronics_store/data/models/cart_model.dart';
import 'package:electronics_store/data/models/favorite_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartModelAdapter());
    registerAdapter(FavoriteModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartModelAdapter());
    registerAdapter(FavoriteModelAdapter());
  }
}
